-- USERS
CREATE TABLE IF NOT EXISTS users (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username    VARCHAR(255) NOT NULL UNIQUE,
  password    VARCHAR(255) NOT NULL,
  email       VARCHAR(255) UNIQUE,
  description TEXT
);

-- roles (ElementCollection)
CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT NOT NULL,
  roles   VARCHAR(50) NOT NULL,
  CONSTRAINT fk_user_roles_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles(user_id);

-- PROJECTS
CREATE TABLE IF NOT EXISTS projects (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255),
  description TEXT,
  created_at  TIMESTAMP,
  owner_id    BIGINT,
  CONSTRAINT fk_projects_owner
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_projects_owner_id ON projects(owner_id);

-- TASKS
CREATE TABLE IF NOT EXISTS tasks (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT,
  title      VARCHAR(255),
  status     VARCHAR(50),
  due_date   TIMESTAMP,
  CONSTRAINT fk_tasks_project
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON tasks(project_id);